#!/bin/bash -xe

## Setup Clojure Dependencies and limit threads to avoid write lock error
cd /home/vscode/workspace
clj -Sthreads 1 -P

## Set Up Python Dependencies
mkdir -p .venv && poetry install

#update vscode user .bashrc to support Clojure + Julia config.
# the shell that spawns the repl must set the JULIA_HOME variable
tee -a /home/vscode/.bashrc <<EOF
export JULIA_HOME=/home/vscode/.julia/juliaup/julia-1.7.3+0.x64.linux.gnu
export PATH=${JULIA_HOME}/bin:$PATH
EOF

## Start Clojure REPLs
clj -M:julia &
clj -M:rrr &
clj -M:apl &
