#!/bin/bash -xe

## Setup Clojure Dependencies and limit threads to avoid write lock error
clj -Sthreads 1 -P

## Set Up Python Dependencies
mkdir -p .venv && poetry install

## Start Clojure REPLs
clj -M:julia &
clj -M:rrr &
clj -M:apl &